-- Drop IMPAcT tables, sequences, functions and users
-- For use in setting up the open source version of the system

-- Drop tables
drop table impact_audit_literal               cascade;
drop table impact_audit_relationship          cascade;
drop table impact_comment                     cascade;
drop table impact_favourite_language          cascade;
drop table impact_help_options                cascade;
drop table impact_help_pages                  cascade;
drop table impact_image                       cascade;
drop table impact_institution                 cascade;
drop table impact_language_of_manifestation   cascade;
drop table impact_language_of_work            cascade;
drop table impact_location                    cascade;
drop table impact_lookup_catalogue            cascade;
drop table impact_lookup_document_type        cascade;
drop table impact_manifestation               cascade;
drop table impact_menu                        cascade;
drop table impact_nationality                 cascade;
drop table impact_nisba                       cascade;
drop table impact_org_subtype                 cascade;
drop table impact_org_type                    cascade;
drop table impact_person                      cascade;
drop table impact_person_summary              cascade;
drop table impact_publication                 cascade;
drop table impact_queryable_work              cascade;
drop table impact_relationship                cascade;
drop table impact_relationship_type           cascade;
drop table impact_report_groups               cascade;
drop table impact_report_outputs              cascade;
drop table impact_reports                     cascade;
drop table impact_resource                    cascade;
drop table impact_role_category               cascade;
drop table impact_roles                       cascade;
drop table impact_sessions                    cascade;
drop table impact_speed_entry_text            cascade;
drop table impact_subject                     cascade;
drop table impact_user_roles                  cascade;
drop table impact_user_saved_queries          cascade;
drop table impact_user_saved_query_selection  cascade;
drop table impact_users                       cascade;
drop table impact_work                        cascade;
drop table impact_work_type                   cascade;

-- Drop sequences
drop sequence impact_audit_id_seq                      ;
drop sequence impact_comment_id_seq                    ;
drop sequence impact_help_options_option_id_seq        ;
drop sequence impact_help_pages_page_id_seq            ;
drop sequence impact_image_id_seq                      ;
drop sequence impact_institution_id_seq                ;
drop sequence impact_location_id_seq                   ;
drop sequence impact_lookup_catalogue_id_seq           ;
drop sequence impact_lookup_document_type_id_seq       ;
drop sequence impact_menu_item_id_seq                  ;
drop sequence impact_menu_order_seq                    ;
drop sequence impact_nationality_id_seq                ;
drop sequence impact_nisba_id_seq                      ;
drop sequence impact_org_subtype_id_seq                ;
drop sequence impact_org_type_id_seq                   ;
drop sequence impact_person_iperson_id_seq             ;
drop sequence impact_publication_id_seq                ;
drop sequence impact_relationship_id_seq               ;
drop sequence impact_report_groups_report_group_id_seq ;
drop sequence impact_reports_report_id_seq             ;
drop sequence impact_resource_id_seq                   ;
drop sequence impact_role_category_id_seq              ;
drop sequence impact_roles_role_id_seq                 ;
drop sequence impact_sessions_session_id_seq           ;
drop sequence impact_speed_entry_text_id_seq           ;
drop sequence impact_subject_id_seq                    ;
drop sequence impact_user_saved_queries_id_seq         ;
drop sequence impact_user_saved_query_selection_id_seq ;
drop sequence impact_users_username_seq                ;
drop sequence impact_work_iwork_id_seq                 ;
drop sequence impact_work_type_id_seq                  ;

-- Drop database functions
drop function  dbf_impact_add_to_rels_decoded_string  ( input_table_name character varying, input_id_value character varying, input_start_date date, input_end_date date, html_output integer, expand_details integer, curr_item integer, input_string text   ) cascade;
drop function  dbf_impact_audit_any ( ) cascade;
drop function  dbf_impact_audit_literal_delete  ( input_table_name character varying, input_key_value_text character varying, input_key_value_integer integer, input_key_decode text, input_column_name character varying, input_old_column_value text  ) cascade;
drop function  dbf_impact_audit_literal_insert  ( input_table_name character varying, input_key_value_text character varying, input_key_value_integer integer, input_key_decode text, input_column_name character varying, input_new_column_value text  ) cascade;
drop function  dbf_impact_audit_literal_update  ( input_table_name character varying, input_key_value_text character varying, input_key_value_integer integer, input_key_decode text, input_column_name character varying, input_new_column_value text, input_old_column_value text   ) cascade;
drop function  dbf_impact_audit_relationship_delete   ( input_left_table_name character varying, input_left_id_value_old character varying, input_left_id_decode_old text, input_relationship_type character varying, input_relationship_decode_left_to_right character varying, input_relationship_decode_right_to_left character varying, input_right_table_name character varying, input_right_id_value_old character varying, input_right_id_decode_old text ) cascade;
drop function  dbf_impact_audit_relationship_insert   ( input_left_table_name character varying, input_left_id_value_new character varying, input_left_id_decode_new text, input_relationship_type character varying, input_relationship_decode_left_to_right character varying, input_relationship_decode_right_to_left character varying, input_right_table_name character varying, input_right_id_value_new character varying, input_right_id_decode_new text ) cascade;
drop function  dbf_impact_audit_relationship_update   ( input_left_table_name character varying, input_left_id_value_new character varying, input_left_id_decode_new text, input_left_id_value_old character varying, input_left_id_decode_old text, input_relationship_type character varying, input_relationship_decode_left_to_right character varying, input_relationship_decode_right_to_left character varying, input_right_table_name character varying, input_right_id_value_new character varying, input_right_id_decode_new text, input_right_id_value_old character varying, input_right_id_decode_old text ) cascade;
drop function  dbf_impact_cascade01_work_changes   ( ) cascade;
drop function  dbf_impact_cascade02_rel_changes ( ) cascade;
drop function  dbf_impact_cascade03_decodes  ( ) cascade;
drop function  dbf_impact_check_login_creds  ( input_username text, input_pw text, input_token text  ) cascade;
drop function  dbf_impact_check_session   ( input_username text, input_session_code text ) cascade;
drop function  dbf_impact_convert_list_from_html   ( input_string text ) cascade;
drop function  dbf_impact_convert_list_to_html  ( input_string text ) cascade;
drop function  dbf_impact_convert_list_to_or_from_html   ( input_string text, html_output integer ) cascade;
drop function  dbf_impact_create_sql_user ( input_username character varying, grant_edit_role character varying  ) cascade;
drop function  dbf_impact_create_user  ( input_username character varying, input_password character varying, input_surname character varying, input_forename character varying, input_email text, grant_edit_role character varying   ) cascade;
drop function  dbf_impact_decode ( table_name character varying, key_value character varying   ) cascade;
drop function  dbf_impact_decode ( table_name character varying, key_value character varying, suppress_links integer   ) cascade;
drop function  dbf_impact_decode ( table_name character varying, key_value character varying, suppress_links integer, expand_details integer   ) cascade;
drop function  dbf_impact_decode_expanded ( table_name character varying, key_value character varying   ) cascade;
drop function  dbf_impact_decode_expanded ( table_name character varying, key_value character varying, suppress_links integer   ) cascade;
drop function  dbf_impact_decode_manifestation  ( key_value character varying   ) cascade;
drop function  dbf_impact_decode_manifestation  ( key_value character varying, suppress_links integer   ) cascade;
drop function  dbf_impact_decode_nisba ( key_value integer ) cascade;
drop function  dbf_impact_decode_nisba ( key_value integer, suppress_links integer ) cascade;
drop function  dbf_impact_decode_person   ( key_value character varying   ) cascade;
drop function  dbf_impact_decode_person   ( key_value character varying, suppress_links integer   ) cascade;
drop function  dbf_impact_decode_person   ( key_value character varying, suppress_links integer, expand_details integer   ) cascade;
drop function  dbf_impact_decode_place_with_region ( place_id character varying ) cascade;
drop function  dbf_impact_decode_username ( input_username text, input_token text  ) cascade;
drop function  dbf_impact_decode_work  ( key_value character varying   ) cascade;
drop function  dbf_impact_decode_work  ( key_value character varying, suppress_links integer   ) cascade;
drop function  dbf_impact_decode_work_role_with_aliases  ( role_code character varying, input_work_id character varying   ) cascade;
drop function  dbf_impact_delete_session  ( session_for_deletion text  ) cascade;
drop function  dbf_impact_delete_user  ( input_username character varying ) cascade;
drop function  dbf_impact_full_manifestation_details  ( input_work_id character varying  ) cascade;
drop function  dbf_impact_get_column_label   ( column_name character varying ) cascade;
drop function  dbf_impact_get_constant_value ( constant_name character varying  ) cascade;
drop function  dbf_impact_get_language_of_manifestation  ( input_manifestation_id character varying  ) cascade;
drop function  dbf_impact_get_language_of_work  ( input_work_id character varying  ) cascade;
drop function  dbf_impact_get_table_label ( table_name character varying  ) cascade;
drop function  dbf_impact_get_work_desc   ( input_work_id character varying  ) cascade;
drop function  dbf_impact_link_to_edit_app   ( link_text character varying, query_string character varying ) cascade;
drop function  dbf_impact_list_addressees ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_addressees_for_display ( work_id_parm text ) cascade;
drop function  dbf_impact_list_addressees_searchable  ( work_id_parm text ) cascade;
drop function  dbf_impact_list_affiliations  ( input_iperson_id integer   ) cascade;
drop function  dbf_impact_list_affiliations  ( input_person_id character varying   ) cascade;
drop function  dbf_impact_list_comments_on_author  ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_comments_on_author_for_display  ( work_id_parm text ) cascade;
drop function  dbf_impact_list_comments_on_author_searchable   ( work_id_parm text ) cascade;
drop function  dbf_impact_list_comments_on_work ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_comments_on_work_for_display ( work_id_parm text ) cascade;
drop function  dbf_impact_list_comments_on_work_searchable  ( work_id_parm text ) cascade;
drop function  dbf_impact_list_creators   ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_creators_for_display   ( work_id_parm text ) cascade;
drop function  dbf_impact_list_creators_searchable ( work_id_parm text ) cascade;
drop function  dbf_impact_list_destinations  ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_destinations_for_display  ( work_id_parm text ) cascade;
drop function  dbf_impact_list_destinations_searchable   ( work_id_parm text ) cascade;
drop function  dbf_impact_list_images_of_work   ( input_id character varying ) cascade;
drop function  dbf_impact_list_lefthand_rel_ids ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_lefthand_rels_decoded  ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying, html_output integer  ) cascade;
drop function  dbf_impact_list_lefthand_rels_decoded  ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying, html_output integer, expand_details integer  ) cascade;
drop function  dbf_impact_list_lefthand_rels_decoded_for_display  ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_lefthand_rels_decoded_searchable   ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_manif_people  ( input_manif_id character varying ) cascade;
drop function  dbf_impact_list_manifestation_images   ( input_id character varying ) cascade;
drop function  dbf_impact_list_manifestations   ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_manifestations_for_display   ( work_id_parm text ) cascade;
drop function  dbf_impact_list_manifestations_searchable ( work_id_parm text ) cascade;
drop function  dbf_impact_list_origins ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_origins_for_display ( work_id_parm text ) cascade;
drop function  dbf_impact_list_origins_searchable  ( work_id_parm text ) cascade;
drop function  dbf_impact_list_people_mentioned ( work_id_parm text, html_output integer ) cascade;
drop function  dbf_impact_list_people_mentioned_for_display ( work_id_parm text ) cascade;
drop function  dbf_impact_list_people_mentioned_searchable  ( work_id_parm text ) cascade;
drop function  dbf_impact_list_rel_ids ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_related_people   ( input_work_id character varying  ) cascade;
drop function  dbf_impact_list_related_people   ( input_work_id integer   ) cascade;
drop function  dbf_impact_list_related_resources   ( input_table character varying, input_id character varying, full_details integer  ) cascade;
drop function  dbf_impact_list_related_works ( input_work_id character varying  ) cascade;
drop function  dbf_impact_list_related_works ( input_work_id integer   ) cascade;
drop function  dbf_impact_list_rels_decoded  ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying, html_output integer  ) cascade;
drop function  dbf_impact_list_rels_decoded  ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying, html_output integer, expand_details integer  ) cascade;
drop function  dbf_impact_list_rels_decoded_for_display  ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_rels_decoded_searchable   ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_righthand_rel_ids   ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_righthand_rels_decoded ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying, html_output integer  ) cascade;
drop function  dbf_impact_list_righthand_rels_decoded ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying, html_output integer, expand_details integer  ) cascade;
drop function  dbf_impact_list_righthand_rels_decoded_for_display ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_righthand_rels_decoded_searchable  ( required_table character varying, required_reltype character varying, known_table character varying, known_id character varying  ) cascade;
drop function  dbf_impact_list_subjects_of_work ( work_id_parm text ) cascade;
drop function  dbf_impact_list_work_resources_brief   ( input_id character varying ) cascade;
drop function  dbf_impact_person_summary  ( input_person_id character varying   ) cascade;
drop function  dbf_impact_person_summary  ( input_person_id character varying, include_works integer ) cascade;
drop function  dbf_impact_person_summary  ( input_person_id character varying, include_works integer, expand_details integer ) cascade;
drop function  dbf_impact_person_summary  ( input_person_id character varying, other_tab character varying, expand_details integer ) cascade;
drop function  dbf_impact_person_summary  ( input_person_id character varying, other_tab character varying, expand_details integer, result_column character varying ) cascade;
drop function  dbf_impact_person_summary  ( input_person_id integer ) cascade;
drop function  dbf_impact_person_summary  ( input_person_id integer, include_works integer  ) cascade;
drop function  dbf_impact_person_summary_with_works   ( input_person_id character varying   ) cascade;
drop function  dbf_impact_person_summary_with_works   ( input_person_id integer ) cascade;
drop function  dbf_impact_primary_key  ( the_table_name character varying ) cascade;
drop function  dbf_impact_refresh_language_of_manifestation ( ) cascade;
drop function  dbf_impact_refresh_language_of_work ( ) cascade;
drop function  dbf_impact_refresh_person_summary   ( input_id character varying ) cascade;
drop function  dbf_impact_refresh_person_summary   ( input_id integer  ) cascade;
drop function  dbf_impact_refresh_person_summary   ( input_text_id character varying, input_integer_id integer   ) cascade;
drop function  dbf_impact_refresh_queryable_work   ( input_work_id character varying  ) cascade;
drop function  dbf_impact_refresh_work_desc  ( input_work_id character varying  ) cascade;
drop function  dbf_impact_save_session_data  ( input_username text, old_session text, new_session text  ) cascade;
drop function  dbf_impact_select_user  ( input_username text  ) cascade;
drop function  dbf_impact_select_user_role_ids  ( input_username character varying ) cascade;
drop function  dbf_impact_select_user_roles  ( input_username character varying ) cascade;
drop function  dbf_impact_set_change_cols ( ) cascade;
drop function  dbf_impact_set_pw_by_super ( md5_user_name character varying, token character varying, md5_pass character varying   ) cascade;
drop function  dbf_impact_set_user_login_status ( input_username character varying, input_active integer   ) cascade;
drop function  dbf_impact_set_user_roles  ( input_username character varying, input_roles character varying   ) cascade;
drop function  dbf_impact_update_user_details   ( input_username character varying, input_surname character varying, input_forename character varying, input_email text   ) cascade;
drop function  impact_common_get_orig_column_name  ( text_id character varying  ) cascade;
drop function  impact_common_get_orig_id  ( text_id character varying  ) cascade;
drop function  impact_common_get_orig_table_name   ( text_id character varying  ) cascade;
drop function  impact_common_make_text_id ( orig_table_name character varying, orig_column_name character varying, orig_row_id integer   ) cascade;


-- Drop miscellaneous bits and bobs
drop view impact_audit_trail_table_view;
drop type impact_rel_one_side;


-- Drop users created for example database
drop user impacta1supr       ;
drop user w5view             ;
drop user x0minim            ;

drop role super_role_impact  ;
drop role editor_role_impact ;
drop role viewer_role_impact ;

